<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Events\PlaceUpdatedDomainEvent.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\YallaJo.SharedKernel.Domain\YallaJo.SharedKernel.Domain.csproj" />
  </ItemGroup>
</Project>
