<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accounts.Domain\Accounts.Domain.csproj" />
    <ProjectReference Include="..\Accounts.Infrastructure\Accounts.Infrastructure.csproj" />
    <ProjectReference Include="..\YallaJo.SharedKernel\YallaJo.SharedKernel.csproj" />
  </ItemGroup>

</Project>
