<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.12.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.15" />
    <PackageReference Include="Stubble.Core" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounts.Contracts\Accounts.Contracts.csproj" />
    <ProjectReference Include="..\Auth.Contracts\Auth.Contracts.csproj" />
    <ProjectReference Include="..\Booking.Contracts\Booking.Contracts.csproj" />
    <ProjectReference Include="..\ContentTours.Contracts\ContentTours.Contracts.csproj" />
    <ProjectReference Include="..\ContentPlaces.Contracts\ContentPlaces.Contracts.csproj" />
    <ProjectReference Include="..\Finance.Contracts\Finance.Contracts.csproj" />
    <ProjectReference Include="..\Messaging.Application\Messaging.Application.csproj" />
    <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
    <ProjectReference Include="..\Social.Contracts\Social.Contracts.csproj" />
    <ProjectReference Include="..\ContentBlogs.Contracts\ContentBlogs.Contracts.csproj" />
    <ProjectReference Include="..\Messaging.Domain\Messaging.Domain.csproj" />
    <ProjectReference Include="..\YallaJo.SharedKernel.Infrastructure\YallaJo.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>
</Project>
