<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="EventHandlers\**" />
    <EmbeddedResource Remove="EventHandlers\**" />
    <None Remove="EventHandlers\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContentCore.Contracts\ContentCore.Contracts.csproj" />
    <ProjectReference Include="..\ContentCore.Domain\ContentCore.Domain.csproj" />
    <ProjectReference Include="..\YallaJo.SharedKernel.Application\YallaJo.SharedKernel.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Commands\Category\CreateCategory\CreateCategoryResult.cs" />
  </ItemGroup>
</Project>
