// <copyright file="SitemapRegenerationService.cs" company="YallaJo">
// Copyright (c) YallaJo. All rights reserved.
// </copyright>

namespace ContentSeo.Infrastructure.BackgroundServices;

using ContentSeo.Application.Interfaces;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

internal sealed class SitemapRegenerationService(
    IServiceScopeFactory scopeFactory,
    ILogger<SitemapRegenerationService> logger) : BackgroundService
{
    private static readonly TimeSpan Interval = TimeSpan.FromHours(6);

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        logger.LogInformation("SitemapRegenerationService started; interval={Interval}", Interval);

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await using var scope = scopeFactory.CreateAsyncScope();
                var renderer = scope.ServiceProvider.GetRequiredService<ISitemapRenderer>();
                await renderer.RenderAndCacheAsync(stoppingToken).ConfigureAwait(false);
                logger.LogInformation("Sitemap regenerated by background service.");
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
#pragma warning disable CA1031
            catch (Exception ex)
#pragma warning restore CA1031
            {
                logger.LogError(ex, "SitemapRegenerationService iteration failed; will retry on next interval.");
            }

            try
            {
                await Task.Delay(Interval, stoppingToken).ConfigureAwait(false);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
        }

        logger.LogInformation("SitemapRegenerationService stopped.");
    }
}
