<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accounts.Application\Accounts.Application.csproj" />
    <ProjectReference Include="..\Accounts.Contracts\Accounts.Contracts.csproj" />
    <ProjectReference Include="..\Accounts.Domain\Accounts.Domain.csproj" />
    <ProjectReference Include="..\YallaJo.SharedKernel.Infrastructure\YallaJo.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
