<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Booking.Contracts\Booking.Contracts.csproj" />
    <ProjectReference Include="..\ContentPlaces.Contracts\ContentPlaces.Contracts.csproj" />
    <ProjectReference Include="..\ContentTours.Contracts\ContentTours.Contracts.csproj" />
    <ProjectReference Include="..\Security.Contracts\Security.Contracts.csproj" />
    <ProjectReference Include="..\Social.Contracts\Social.Contracts.csproj" />
    <ProjectReference Include="..\Social.Domain\Social.Domain.csproj" />
    <ProjectReference Include="..\YallaJo.SharedKernel.Application\YallaJo.SharedKernel.Application.csproj" />
  </ItemGroup>
</Project>
