// <copyright file="SitemapRegenerationService.cs" company="YallaJo">
// Copyright (c) YallaJo. All rights reserved.
// </copyright>

namespace ContentSeo.Infrastructure.BackgroundServices;

using ContentSeo.Application.Interfaces;
using ContentSeo.Domain.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

internal sealed class SitemapRegenerationService(
    IServiceScopeFactory scopeFactory,
    ILogger<SitemapRegenerationService> logger) : BackgroundService
{
    /// <summary>
    /// PDF §8: sitemap regenerated every 6 hours at 00:00, 06:00, 12:00, 18:00 UTC.
    /// </summary>
    private static readonly int[] SlotHoursUtc = [0, 6, 12, 18];

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        logger.LogInformation(
            "SitemapRegenerationService started; slots={Slots} UTC",
            string.Join(",", SlotHoursUtc));

        while (!stoppingToken.IsCancellationRequested)
        {
            // ── Wait until the next cron slot ─────────────────────────────────
            var delay = DelayUntilNextSlot();
            logger.LogDebug("SitemapRegenerationService: next run in {Delay}", delay);

            try
            {
                await Task.Delay(delay, stoppingToken).ConfigureAwait(false);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }

            // ── Render ────────────────────────────────────────────────────────
            try
            {
                await using var scope = scopeFactory.CreateAsyncScope();
                var renderer = scope.ServiceProvider.GetRequiredService<ISitemapRenderer>();
                await renderer.RenderAndCacheAsync(stoppingToken).ConfigureAwait(false);
                logger.LogInformation("Sitemap regenerated by background service at {UtcNow:O}.", DateTime.UtcNow);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
#pragma warning disable CA1031
            catch (Exception ex)
#pragma warning restore CA1031
            {
                logger.LogError(ex, "SitemapRegenerationService iteration failed; will retry on next slot.");
            }
        }

        logger.LogInformation("SitemapRegenerationService stopped.");
    }

    /// <summary>
    /// Returns the <see cref="TimeSpan"/> until the next cron slot (00/06/12/18 UTC).
    /// Minimum 1 second to avoid tight-loop if called exactly on a slot boundary.
    /// </summary>
    internal static TimeSpan DelayUntilNextSlot()
    {
        var now = DateTime.UtcNow;
        var todaySlots = SlotHoursUtc
            .Select(h => new DateTime(now.Year, now.Month, now.Day, h, 0, 0, DateTimeKind.Utc))
            .ToList();

        var next = todaySlots.FirstOrDefault(s => s > now);
        if (next == default)
        {
            // All today's slots have passed — use first slot tomorrow.
            next = todaySlots[0].AddDays(1);
        }

        var delay = next - now;
        return delay < TimeSpan.FromSeconds(1) ? TimeSpan.FromSeconds(1) : delay;
    }
}
