<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Modules\Security\Features\AuditLogs\Requests\" />
    <Folder Include="Areas\Admin\Modules\Security\Features\AuditLogs\Validators\" />
    <Folder Include="Areas\Admin\Modules\Security\Features\Roles\Validators\" />
    <Folder Include="Areas\Admin\Modules\Security\Features\Users\Validators\" />
    <Folder Include="Areas\Auth\Features\Devices\" />
    <Folder Include="Areas\Auth\Features\ExternalProviders\Mappers\" />
    <Folder Include="Areas\Auth\Features\ExternalProviders\Validators\" />
    <Folder Include="Areas\Auth\Features\ForgotPassword\Validators\" />
    <Folder Include="Areas\Auth\Features\ForgotPassword\Views\" />
    <Folder Include="Areas\Auth\Features\ForgotPassword\ViewModels\" />
    <Folder Include="Areas\Auth\Features\ForgotPassword\Responses\" />
    <Folder Include="Areas\Auth\Features\ForgotPassword\Requests\" />
    <Folder Include="Areas\Auth\Features\Login\Views\" />
    <Folder Include="Areas\Auth\Features\Logout\Responses\" />
    <Folder Include="Areas\Auth\Features\Sessions\Validators\" />
    <Folder Include="Areas\Auth\Features\ResetPassword\" />
    <Folder Include="Controllers\" />
    <Folder Include="Infrastructure\Api\Core\" />
    <Folder Include="Infrastructure\Api\Handlers\" />
    <Folder Include="Infrastructure\Authentication\Claims\" />
    <Folder Include="Infrastructure\Authentication\Cookie\" />
    <Folder Include="Infrastructure\Authentication\SignIn\" />
    <Folder Include="Infrastructure\Authentication\Tokens\" />
    <Folder Include="Infrastructure\Constants\" />
    <Folder Include="Infrastructure\DependencyInjection\" />
    <Folder Include="Infrastructure\Navigation\" />
    <Folder Include="Infrastructure\State\" />
    <Folder Include="Models\" />
    <Folder Include="Shared\Components\" />
    <Folder Include="Shared\Extensions\" />
    <Folder Include="Shared\Filters\" />
    <Folder Include="Shared\Layout\" />
    <Folder Include="Shared\Notifications\" />
    <Folder Include="Shared\Results\" />
    <Folder Include="Shared\TagHelpers\" />
    <Folder Include="Shared\ViewModels\" />
    <Folder Include="Shared\Views\" />
  </ItemGroup>

</Project>
